version: '3'

volumes:
  instaMongo:
  instaCassandra:

services:
  auth:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
    image: devmiguelangel/insta_service:latest
    container_name: my_auth_service
    volumes:
      - ./auth-service:/app
    ports:
      - '8000:8000'
    restart: unless-stopped
    # tty: true

  # kafka:
  #   image: bitnami/kafka:3.6.0
  #   container_name: my_kafka
  #   ports:
  #     - '9092:9092'
  #   environment:
  #     # - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
  #     # - KAFKA_ADVERTISED_PORT=9092
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #   depends_on:
  #     - zookeeper

  # zookeeper:
  #   image: bitnami/zookeeper:3.9.1
  #   container_name: my_zookeeper
  #   ports:
  #     - '2181:2181'
  #   # environment:
  #   #   - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  # mongodb:
  #   image: mongo:7.0.3
  #   container_name: my_mongodb
  #   # environment:
  #   #   - MONGO_LOG_DIR=/dev/null
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - instaMongo:/data/db

  # neo4j:
  #   image: neo4j:5.13
  #   container_name: my_neo4j
  #   ports:
  #    - 7474:7474
  #    - 7687:7687

  # cassandra:
  #   image: cassandra:4.1
  #   container_name: my_cassandra
  #   ports:
  #     - 7000:7000
  #     - 9042:9042
  #   volumes:
  #     - instaCassandra:/var/lib/cassandra
